name: CICD

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
      - "move-reading-to-rust"

jobs:
  lint-build-deploy:
    name: Lint, test, and build
    runs-on: ubuntu-latest
    container: zaksabeast/devkita64-rust
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Lint
        run: make -C libs/csight-core lint

      - name: Test
        run: make -C libs/csight-core test

      - name: Build
        run: make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CaptureSight
          retention-days: 5
          path: out/capturesight.ovl

      - name: Draft release
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: out/capturesight.ovl
